ERROR - 2023-01-17 09:07:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\progma\app\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\progma\app\Controllers\Auth\Login.php(12): App\Models\Msuser->getAll()
#6 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
#7 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#8 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\progma\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\progma\app\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\progma\app\Controllers\Auth\Login.php(12): App\Models\Msuser->getAll()
#5 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
#6 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#7 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\progma\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-01-17 09:07:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `msuser`', [], false)
 3 APPPATH\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth\Login.php(12): App\Models\Msuser->getAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-17 16:09:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\progma\app\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\progma\app\Controllers\Auth\Login.php(12): App\Models\Msuser->getAll()
#6 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
#7 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#8 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\progma\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\progma\app\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\progma\app\Controllers\Auth\Login.php(12): App\Models\Msuser->getAll()
#5 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
#6 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#7 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\progma\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-01-17 16:09:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `msuser`', [], false)
 3 APPPATH\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth\Login.php(12): App\Models\Msuser->getAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-17 16:12:11 --> Call to a member function getAll() on null
in APPPATH\Controllers\Auth\Login.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-17 16:12:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\progma\app\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\progma\app\Controllers\Auth\Login.php(17): App\Models\Msuser->getAll()
#6 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
#7 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#8 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\progma\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\progma\app\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\progma\app\Controllers\Auth\Login.php(17): App\Models\Msuser->getAll()
#5 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
#6 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#7 C:\xampp\htdocs\progma\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\progma\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-01-17 16:12:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `msuser`', [], false)
 3 APPPATH\Models\Msuser.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth\Login.php(17): App\Models\Msuser->getAll()
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-17 17:41:02 --> Undefined variable: dt
in APPPATH\Controllers\Auth\Login.php on line 11.
 1 APPPATH\Controllers\Auth\Login.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: dt', 'APPPATH\\Controllers\\Auth\\Login.php', 11, [])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth\Login->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
